language: go
go:
  - "1.9.4"
  - "1.10"
sudo: false
install:
  - GLIDE_TAG=v0.12.3
  - GLIDE_DOWNLOAD="https://github.com/Masterminds/glide/releases/download/$GLIDE_TAG/glide-$GLIDE_TAG-linux-amd64.tar.gz"
  - curl -L $GLIDE_DOWNLOAD | tar -xvz
  - export PATH=$PATH:$PWD/linux-amd64/
  - mkdir -p $GOPATH/src/github.com/bcext/
  - pushd $GOPATH/src/github.com/bcext/
  - git clone https://github.com/bcext/gcash
  - pushd gcash
  - $GOPATH/src/github.com/bcext/neutrino/gcash_checkout.sh
  - glide install
  - go install . ./cmd/...
  - popd
  - popd
env:
  matrix:
    - RACE=false
    - RACE=true
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - ./gotest.sh
